#!/bin/bash

ffmpeg -s 1280x720 -f video4linux2 -i /dev/video10 -vframes 1 /samba/photo/$(date "+%Y%m%d%H%M").jpeg
echo "$(date): $? ." >> /samba/take_photo.log


# ffmpeg -framerate 15 -pattern_type glob -i '/samba/photo/*.jpeg' -vcodec mpeg4 /samba/movie.avi
